print(int(5+5))
print(int(5-5))
print(int(5*5))
print(int(5/5))
print(int(5**5))
print(int(5//5))
print(int(5%5))

print(int(5+3*2))
print(int(3*5+4**2))
print(int(3*(5+4)**2))

print("oi"*5)

nome=input("qual é o seu nome ?")
print("muito prazer em conhecer você ","{}".format(nome))
print("muito prazer em conhecer você {:20}!".format(nome))
print("muito prazer em conhecer você {:>20}!".format(nome))
print("muito prazer em conhecer você {:^20}!".format(nome))
print("muito prazer em conhecer você {:=^20}!".format(nome))

print("Vamos agora praticar a execução dos operadores aritméticos que vimos nesta aula")
n1=int(input("escreva um numero:"))
n2=int(input(" agora , por favor, escreva um outro:"))
print("Os valores somados é  {}".format(n1+n2))
print("Os valores subtraidos é {}".format(n1-n2))
print(" Os valores multiplicados é {}".format(n1*n2))
print("Os valores divididos é {}".format(n1/n2))
print("caso a divisão tenha dado um numero alto , sua aproximação é {:.3f}".format(n1/n2))
print("O primeiro valor elevado ao segundo valor é {}".format(n1**n2))
print("A divisão inteira dos valores é {}".format(n1//n2))
print("O resto da divisão dos valores é {}".format(n1%n2))