frase = ("curso em video python")
print("{}".format(frase))
print(frase[9])
print(frase[9:13])
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])

print(len(frase))
print(frase.count("o"))
print(frase.count("o",0,13))
print(frase.find("deo"))
print(frase.find("android"))
print("curso"in frase)

print(frase.replace("python","android"))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())

frase2=("   aprenda python  ")
print(len(frase2))
print("{}".format(frase2))
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())

print(frase.split())
divisão= frase.split()
print(divisão[1])
print(divisão[2][4])
print("-".join(frase))

