conteudo=input("digite algo:")
print("o tipo primitivo desse valor é ",type(conteudo))
print("o conteudo é numérico ?",conteudo.isnumeric())
print("o conteudo é alfabetico ?",conteudo.isalpha())
print("o conteudo é decimal ?",conteudo.isdecimal())
print("o conteudo somente tem espaço ?",conteudo.isspace())
print("ele é alfanumérico ? ",conteudo.isalnum())
print("Agora vamos tentar de uma forma mais atualizada para fazer este exercício ")
conteudo2=input("digite algo:")
#print(" o tipo primitivo é ",type({}).format(conteudo2))
print(" o conteudo é numérico ?","{}".format(conteudo2).isnumeric())
print(" o conteudo é alfabético ?","{}".format(conteudo2).isalpha())
print("o conteudo é decimal ?","{}".format(conteudo2).isdecimal())
print("o conteudo somente tem espaço ?","{}".format(conteudo2).isspace())
print("o conteudo é alfanumérico ?","{}".format(conteudo2).isalnum())