print("Agora vamos ter que mostrar a tabuada do valor que for digitado")
n5=int(input("digite o numero que gostaria de saber a tabuada:"))
print(" a tabuada do valor digitado é ")
print(n5,"x 1 =",n5*1)
#print(" {} x {} = {}".format(n5 , 1 , n5*1)) versão do professor
print(n5,"x 2 = ",n5*2)
print(n5,"x 3 = ",n5*3)
print(n5,"x 4 =",n5*4)
print(n5,"x 5 = ",n5*5)
print(n5,"x 6 = ",n5*6)
print(n5,"x 7 = ",n5*7)
print(n5,"x 8 = ",n5*8)
print(n5,"x 9 = ",n5*9)
print(n5,"x 10 = ",n5*10)